.TH EMBOSS-ESIM4 1 "2025-10-23" "embossers 0.1.28" "User Commands"
.SH NAME
emboss-esim4 \- Splice-aware EST vs genome alignment (approximation of EMBASSY esim4).
.SH SYNOPSIS
emboss esim4 --transcript est.fa --genome genome.fa [--outfile FILE]

.SH DESCRIPTION
Splice-aware EST vs genome alignment (approximation of EMBASSY esim4).
.SH OPTIONS
.TP
\fB--transcript\fR FILE   \fB--genome\fR FILE
.TP
\fB--outfile\fR FILE

.SH EXAMPLES
.TP
emboss esim4 --transcript est.fa --genome chr.fa --outfile esim4.txt
.SH SEE ALSO
emboss(1)
