.TH EMBOSS-NEEDLE 1 "2025-10-23" "embossers 0.1.28" "User Commands"
.SH NAME
emboss-needle \- Needleman–Wunsch global alignment with affine gaps.
.SH SYNOPSIS
emboss needle \fB--asequence\fR FILE   \fB--bsequence\fR FILE
\fB--matrix\fR dna|blosum62
\fB--gapopen\fR N.N   \fB--gapextend\fR N.N
[--match-score N --mismatch -N] [--outfile FILE]
.SH DESCRIPTION
Needleman–Wunsch global alignment with affine gaps.
.SH OPTIONS
.TP
\fB--asequence\fR FILE   \fB--bsequence\fR FILE
.TP
\fB--matrix\fR dna|blosum62
.TP
\fB--gapopen\fR N.N   \fB--gapextend\fR N.N
.TP
\fB--match-score\fR N  \fB--mismatch\fR -N
.TP
\fB--outfile\fR FILE

.SH EXAMPLES
.TP
emboss needle --asequence a.fa --bsequence b.fa --matrix dna --match-score 2 --mismatch -1 --gapopen 10 --gapextend 0.5 --outfile needle.txt
.SH SEE ALSO
emboss(1)
