.TH EMBOSS-MEGAMERGER 1 "2025-10-23" "embossers 0.1.28" "User Commands"
.SH NAME
emboss-megamerger \- Merge two protein sequences by best local overlap; 'X' for conflicts.
.SH SYNOPSIS
emboss megamerger \fB--asequence\fR FILE   \fB--bsequence\fR FILE
[--matrix blosum62] \fB--gapopen\fR N.N   \fB--gapextend\fR N.N
[--minscore N] [--outfile FILE] [--id ID]

.SH DESCRIPTION
Merge two protein sequences by best local overlap; 'X' for conflicts.
.SH OPTIONS
.TP
\fB--asequence\fR FILE   \fB--bsequence\fR FILE
.TP
\fB--matrix\fR blosum62
.TP
\fB--gapopen\fR N.N   \fB--gapextend\fR N.N
.TP
\fB--minscore\fR N  \fB--outfile\fR FILE  \fB--id\fR ID

.SH EXAMPLES
.TP
emboss megamerger --asequence a.fa --bsequence b.fa --outfile merged.fa
.SH SEE ALSO
emboss(1)
